# Generated by Django 5.0.3 on 2024-03-26 17:43

import apps.users.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=30, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(choices=[('М', 'Мужской'), ('Ж', 'Женский')], default='Ж', max_length=1)),
                ('password', models.CharField(max_length=128)),
                ('reset_code', models.CharField(blank=True, max_length=4, null=True)),
            ],
            managers=[
                ('objects', apps.users.manager.UserManager()),
            ],
        ),
    ]
